language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
env:
  jobs:
  - PACKAGE="ptt" OCAML_VERSION=4.08 TESTS=true
  - PACKAGE="ptt" OCAML_VERSION=4.09 TESTS=true
  - PACKAGE="ptt" OCAML_VERSION=4.10 TESTS=true
  - PACKAGE="ptt" OCAML_VERSION=4.11 TESTS=true
